# This is a basic workflow to help you get started with Actions

name: Update Arknights Game Data

# Controls when the workflow will run
on:
  # every day at midnight
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
                          
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Clone source repo
        run: |
          git clone --depth=1 https://github.com/PuppiizSunniiz/Arknight-Images temp-images

      - name: Copy to arknights/img
        run: |
          mkdir -p arknights/img
          rm -rf arknights/img/*

      - name: Copy to arknights/img
        run: |
          mkdir -p arknights/img
          rm -rf arknights/img/*
          
          cp -r temp-images/avatars arknights/img/
          cp -r temp-images/characters arknights/img/
          cp -r temp-images/classes arknights/img/
          cp -r temp-images/equip arknights/img/
          cp -r temp-images/factions arknights/img/
          cp -r temp-images/items arknights/img/
          cp -r temp-images/skills arknights/img/
          cp -r temp-images/portraits arknights/img/
          cp -r temp-images/skingroups arknights/img/

      - name: Commit and push changes
        run: |
          git config user.name "MangoBot"
          git config user.email "actions@github.com"
          git config http.postBuffer 524288000

      - name: Sync Arknights Avatars
        run: |
          git add arknights/img/avatars
          git commit -m "Sync Arknights Avatars" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
      - name: Sync Arknights Characters
        run: |
          FILE_LIST=$(find arknights/img/characters -type f)
          COUNT=0
          BATCH=()
      
          for FILE in $FILE_LIST; do
            BATCH+=("$FILE")
            ((COUNT++))
      
            if (( COUNT % 500 == 0 )); then
              echo "Committing batch of 500 files..."
              git add "${BATCH[@]}"
              git commit -m "Sync Arknights Characters (batch $((COUNT / 500)))"
              BATCH=()
              git push
            fi
          done
      
          # Commit remaining files if any
          if (( ${#BATCH[@]} > 0 )); then
            echo "Committing remaining ${#BATCH[@]} files..."
            git add "${BATCH[@]}"
            git commit -m "Sync Arknights Characters (final batch)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
