# This is a basic workflow to help you get started with Actions

name: Update Arknights Game Data

# Controls when the workflow will run
on:
  # every day at midnight
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
                          
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Clone source repo
        run: |
          git clone --depth=1 https://github.com/PuppiizSunniiz/Arknight-Images temp-images

      - name: Create img dir
        run: |
          mkdir -p arknights/img
          rm -rf arknights/img/*

      - name: Split file folders
        run: |
          mkdir -p arknights/img
          rm -rf arknights/img/*
          
          cp -r temp-images/avatars arknights/img/
          cp -r temp-images/characters arknights/img/
          cp -r temp-images/classes arknights/img/
          cp -r temp-images/equip arknights/img/
          cp -r temp-images/factions arknights/img/
          cp -r temp-images/items arknights/img/
          cp -r temp-images/skills arknights/img/
          cp -r temp-images/portraits arknights/img/
          cp -r temp-images/skingroups arknights/img/
          cp -r temp-images/ui arknights/img/

      - name: Setup User
        run: |
          git config user.name "MangoBot"
          git config user.email "actions@github.com"
          git config http.postBuffer 524288000

      - name: Sync Arknights Avatars
        run: |
          git add arknights/img/avatars
          git commit -m "Sync Arknights Avatars" || echo "No changes to avatars to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Arknights Classes
        run: |
          git add arknights/img/classes
          git commit -m "Sync Arknights classes" || echo "No changes to classes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Arknights items
        run: |
          git add arknights/img/items
          git commit -m "Sync Arknights items" || echo "No changes to items to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Arknights portraits
        run: |
          git add arknights/img/portraits
          git commit -m "Sync Arknights portraits" || echo "No changes to portraits to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Arknights skills
        run: |
          git add arknights/img/skills
          git commit -m "Sync Arknights skills" || echo "No changes to skills to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Arknights factions
        run: |
          git add arknights/img/factions
          git commit -m "Sync Arknights factions" || echo "No changes to factions to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Sync Arknights skingroups
        run: |
          git add arknights/img/skingroups
          git commit -m "Sync skingroups" || echo "No changes to skingroups to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Arknights equip
        run: |
          git add arknights/img/equip
          git commit -m "Sync equip" || echo "No changes to equip to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Arknights ui
        run: |
          git add arknights/img/ui
          git commit -m "Sync ui" || echo "No changes to ui to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Sync Arknights Characters
        run: |
          FILES=( $(find arknights/img/characters -type f | sort) )
          TOTAL=${#FILES[@]}
          CHUNK=$(( (TOTAL + 2) / 3 ))
          
          echo "Total files: $TOTAL"
          echo "Files per chunk: $CHUNK"
          echo "Committing portion 1..."
          git add "${FILES[@]:0:$CHUNK}"
          git commit -m "Sync Arknights Characters (portion 1)" || echo "No changes in portion 1"
          git push
          
          # Second portion
          echo "Committing portion 2..."
          git add "${FILES[@]:$CHUNK:$CHUNK}"
          git commit -m "Sync Arknights Characters (portion 2)" || echo "No changes in portion 2"
          git push
          
          # Third portion
          echo "Committing portion 3..."
          REMAINING=$((TOTAL - CHUNK * 2))
          git add "${FILES[@]:$((CHUNK * 2)):$REMAINING}"
          git commit -m "Sync Arknights Characters (portion 3)" || echo "No changes in portion 3"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
